# Generated by Django 4.2.5 on 2023-09-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_finish_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Upholstery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upholstery_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niksari.material')),
                ('surface_finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niksari.surfacefinish')),
                ('upholstery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niksari.upholstery')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_name', models.CharField(max_length=50)),
                ('furniture_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niksari.category')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niksari.material')),
                ('surface_finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niksari.surfacefinish')),
                ('upholstery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niksari.upholstery')),
            ],
        ),
    ]
