# Generated by Django 4.2.5 on 2023-09-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niksari', '0002_category_furtnituremodel_delete_model_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FurtnitureModel',
            new_name='FurnitureModel',
        ),
    ]
