# Generated by Django 4.2.5 on 2023-11-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niksari', '0003_furnitureimage_remove_furnituremodel_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction_name',
            field=models.CharField(default='instruction', max_length=30),
        ),
    ]
