# Generated by Django 4.2.5 on 2023-11-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niksari', '0005_alter_furnitureimage_image_model_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furnitureimage',
            old_name='image_model_name',
            new_name='image_name',
        ),
    ]
